package lima

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/davidsenack/agentbox/internal/config"
)

const limaTemplateContent = `# AgentBox Lima VM Configuration
# Generated by agentbox - do not edit manually

vmType: "vz"
vmOpts:
  vz:
    rosetta:
      enabled: true
      binfmt: true

cpus: {{ .Config.VM.CPUs }}
memory: "{{ .Config.VM.Memory }}"
disk: "{{ .Config.VM.Disk }}"

images:
  # Pre-built AgentBox images with all tools installed
  - location: "https://github.com/davidsenack/agentbox/releases/download/image-v1.0.0/agentbox-ubuntu-24.04-arm64.qcow2"
    arch: "aarch64"
  - location: "https://github.com/davidsenack/agentbox/releases/download/image-v1.0.0/agentbox-ubuntu-24.04-amd64.qcow2"
    arch: "x86_64"
  # Fallback to stock Ubuntu if pre-built image unavailable
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"

# CRITICAL: Only mount workspace and artifacts - nothing else
mounts:
  - location: "{{ .WorkspacePath }}"
    mountPoint: "/workspace"
    writable: true
  - location: "{{ .ArtifactsPath }}"
    mountPoint: "/artifacts"
    writable: true

# Network: use Lima's default networking (user-v2)
# This provides outbound internet access and host connectivity via socket forwarding

# SSH configuration - no forwarding
ssh:
  localPort: 0
  forwardAgent: false
  forwardX11: false

# Provision scripts run as root
provision:
  - mode: system
    script: |
{{ .ProvisionScript | indent 6 }}

# Readiness probe
probes:
  - mode: readiness
    description: "Waiting for agentbox setup"
    script: |
      #!/bin/bash
      test -f /etc/agentbox-ready
    hint: "Run 'agentbox reset <name>' if this fails"

# Environment propagation is disabled - secrets injected explicitly
propagateProxyEnv: false

# Plain mode disabled - we need cloud-init for user creation
plain: false

# CA certificates - keep defaults
caCerts:
  removeDefaults: false

# Containerd disabled - no Docker socket
containerd:
  system: false
  user: false
`

func indent(spaces int, v string) string {
	pad := strings.Repeat(" ", spaces)
	lines := strings.Split(v, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = pad + line
		}
	}
	return strings.Join(lines, "\n")
}

// GenerateTemplate creates a Lima YAML template for the given configuration
func GenerateTemplate(cfg *config.Config, projectDir string) (string, error) {
	funcMap := template.FuncMap{
		"indent": func(spaces int, v string) string {
			return indent(spaces, v)
		},
	}

	tmpl, err := template.New("lima").Funcs(funcMap).Parse(limaTemplateContent)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	provisionScript := generateProvisionScript(cfg)

	data := struct {
		Config          *config.Config
		WorkspacePath   string
		ArtifactsPath   string
		ProvisionScript string
	}{
		Config:          cfg,
		WorkspacePath:   filepath.Join(projectDir, "workspace"),
		ArtifactsPath:   filepath.Join(projectDir, "artifacts"),
		ProvisionScript: provisionScript,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// GenerateTemplateGasTown creates a Lima YAML template for Gas Town rigs
// The rig is built inside the VM on first boot using the provided repo URL
func GenerateTemplateGasTown(cfg *config.Config, projectDir string, rigName string, repoURL string) (string, error) {
	funcMap := template.FuncMap{
		"indent": func(spaces int, v string) string {
			return indent(spaces, v)
		},
	}

	tmpl, err := template.New("lima").Funcs(funcMap).Parse(limaTemplateContent)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	// Use Gas Town specific provision script with repo URL
	provisionScript := generateProvisionScriptGasTown(cfg, rigName, repoURL)

	data := struct {
		Config          *config.Config
		WorkspacePath   string
		ArtifactsPath   string
		ProvisionScript string
	}{
		Config:          cfg,
		WorkspacePath:   filepath.Join(projectDir, "workspace"),
		ArtifactsPath:   filepath.Join(projectDir, "artifacts"),
		ProvisionScript: provisionScript,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

func generateProvisionScript(cfg *config.Config) string {
	return fmt.Sprintf(`#!/bin/bash
set -euo pipefail

# =============================================================================
# AgentBox Guest Provisioning Script
# Detects pre-built image vs stock Ubuntu and provisions accordingly
# =============================================================================

export DEBIAN_FRONTEND=noninteractive

echo "Starting AgentBox provisioning..."

# Check if running on pre-built AgentBox image
PREBUILT=false
if [ -f /etc/agentbox-image ]; then
    PREBUILT=true
    echo "Detected pre-built AgentBox image - fast provisioning mode"
fi

# --- User Creation (only if not pre-built) ---
if ! id -u agent >/dev/null 2>&1; then
    echo "Creating agent user..."
    useradd -m -s /bin/zsh -G sudo agent
    echo "agent ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/agent
    chmod 0440 /etc/sudoers.d/agent
fi

# --- Proxy Configuration ---
HOST_GATEWAY=$(ip route | grep "default.*lima0" | head -1 | awk '{print $3}' || true)
if [ -z "$HOST_GATEWAY" ]; then
    HOST_GATEWAY=$(ip route | grep default | head -1 | awk '{print $3}' || true)
fi
PROXY_PORT=%d
PROXY_URL="http://${HOST_GATEWAY}:${PROXY_PORT}"

echo "Configuring proxy: ${PROXY_URL}"

# Save proxy config for runtime use (NOT during provisioning)
# Proxy is only needed when user enters the box, not during setup
mkdir -p /etc/agentbox
cat > /etc/agentbox/proxy.conf << EOF
AGENTBOX_PROXY="${PROXY_URL}"
HTTP_PROXY="${PROXY_URL}"
HTTPS_PROXY="${PROXY_URL}"
http_proxy="${PROXY_URL}"
https_proxy="${PROXY_URL}"
NO_PROXY="localhost,127.0.0.1,::1"
no_proxy="localhost,127.0.0.1,::1"
EOF

# Clear any proxy vars during provisioning (direct internet access)
unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy

# --- Full provisioning only if not pre-built ---
if [ "$PREBUILT" = false ]; then
    echo "Stock Ubuntu detected - installing all packages (this takes a while)..."

    # System Packages
    apt-get update
    apt-get install -y \
        zsh build-essential curl wget git jq ripgrep fzf tmux neovim \
        unzip ca-certificates gnupg python3 python3-pip python3-venv

    # Node.js
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
    apt-get update && apt-get install -y nodejs

    # Go
    GO_VERSION="1.22.0"
    ARCH=$(dpkg --print-architecture)
    curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz" | tar -C /usr/local -xzf -
    echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/go.sh

    # Starship
    curl -fsSL https://starship.rs/install.sh | sh -s -- -y

    # mise (needs HOME set)
    export HOME=/root
    curl -fsSL https://mise.run | sh
    mv /root/.local/bin/mise /usr/local/bin/mise 2>/dev/null || true

    # Set zsh as default
    chsh -s /bin/zsh agent

    # Agent directories
    sudo -u agent mkdir -p /home/agent/.local/bin /home/agent/.config/nvim /home/agent/go/bin

    # Oh My Zsh
    sudo -u agent sh -c 'RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

    # .zshrc
    cat > /home/agent/.zshrc << 'ZSHRC'
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git fzf zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
export PATH="$HOME/.local/bin:/usr/local/go/bin:$HOME/go/bin:$PATH"
export GOPATH="$HOME/go"
if [ -f /etc/agentbox/proxy.conf ]; then export $(grep -v '^#' /etc/agentbox/proxy.conf | xargs); fi
eval "$(starship init zsh)"
command -v mise &>/dev/null && eval "$(mise activate zsh)"
cd /workspace 2>/dev/null || true
ZSHRC
    chown agent:agent /home/agent/.zshrc

    # Starship config
    cat > /home/agent/.config/starship.toml << 'STARSHIP'
format = """[agent](bold green)[@](white)[agentbox](bold cyan)[/](white)$directory$git_branch$git_status
[❯](bold green) """
[directory]
truncation_length = 2
truncate_to_repo = false
style = "bold yellow"
format = "[$path]($style) "
[git_branch]
symbol = ""
style = "bold purple"
format = "[$symbol$branch]($style) "
[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style)"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
untracked = "?"
modified = "!"
staged = "+"
deleted = "✘"
[character]
disabled = true
STARSHIP

    # zsh plugins
    git clone https://github.com/zsh-users/zsh-autosuggestions /home/agent/.oh-my-zsh/custom/plugins/zsh-autosuggestions 2>/dev/null || true
    git clone https://github.com/zsh-users/zsh-syntax-highlighting /home/agent/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting 2>/dev/null || true
    chown -R agent:agent /home/agent/.oh-my-zsh

    # Neovim config
    cat > /home/agent/.config/nvim/init.lua << 'NVIM'
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smartindent = true
vim.opt.termguicolors = true
vim.opt.clipboard = "unnamedplus"
vim.g.mapleader = " "
NVIM
    chown -R agent:agent /home/agent/.config

    # AI tools (install globally)
    npm install -g @anthropic-ai/claude-code 2>/dev/null || true
    sudo -u agent bash -c 'export PATH="/usr/local/go/bin:$PATH" GOPATH="$HOME/go"; go install github.com/opencode-ai/opencode@latest' 2>/dev/null || true

    # Gas Town (gt and bd CLIs)
    sudo -u agent bash -c 'export PATH="/usr/local/go/bin:$PATH"; export GOPATH="$HOME/go"; go install github.com/steveyegge/gastown/cmd/gt@latest' 2>/dev/null || true
    sudo -u agent bash -c 'export PATH="/usr/local/go/bin:$PATH"; export GOPATH="$HOME/go"; go install github.com/steveyegge/beads/cmd/bd@latest' 2>/dev/null || true
fi

# --- Gas Town installation (runs for both pre-built and stock) ---
# Install gt and bd if not present (handles pre-built images that may be out of date)
if ! sudo -u agent bash -c 'command -v gt' &>/dev/null || ! sudo -u agent bash -c 'command -v bd' &>/dev/null; then
    echo "Installing Gas Town dependencies..."
    # bd requires libicu-dev for go-icu-regex
    apt-get update -qq && apt-get install -y -qq libicu-dev pkg-config

    if ! sudo -u agent bash -c 'command -v gt' &>/dev/null; then
        echo "Installing Gas Town (gt)..."
        sudo -u agent bash -c 'export PATH="/usr/local/go/bin:$PATH"; export GOPATH="$HOME/go"; go install github.com/steveyegge/gastown/cmd/gt@latest' || echo "Warning: gt installation failed"
    fi
    if ! sudo -u agent bash -c 'command -v bd' &>/dev/null; then
        echo "Installing beads (bd)..."
        sudo -u agent bash -c 'export PATH="/usr/local/go/bin:$PATH"; export GOPATH="$HOME/go"; CGO_ENABLED=1 go install github.com/steveyegge/beads/cmd/bd@latest' || echo "Warning: bd installation failed"
    fi
fi

# --- Prompt config (runs for both pre-built and stock) ---
# Always update Starship config to latest
mkdir -p /home/agent/.config
cat > /home/agent/.config/starship.toml << 'STARSHIP'
format = """[agent](bold green)[@](white)[agentbox](bold cyan)[/](white)$directory$git_branch$git_status
[❯](bold green) """
[directory]
truncation_length = 2
truncate_to_repo = false
style = "bold yellow"
format = "[$path]($style) "
[git_branch]
symbol = ""
style = "bold purple"
format = "[$symbol$branch]($style) "
[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style)"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
untracked = "?"
modified = "!"
staged = "+"
deleted = "✘"
[character]
disabled = true
STARSHIP
chown -R agent:agent /home/agent/.config

# Install zsh plugins if missing
if [ ! -d /home/agent/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions /home/agent/.oh-my-zsh/custom/plugins/zsh-autosuggestions 2>/dev/null || true
fi
if [ ! -d /home/agent/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting /home/agent/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting 2>/dev/null || true
fi
chown -R agent:agent /home/agent/.oh-my-zsh 2>/dev/null || true

# Update .zshrc to use new plugins
cat > /home/agent/.zshrc << 'ZSHRC'
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git fzf zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
export PATH="$HOME/.local/bin:/usr/local/go/bin:$HOME/go/bin:$PATH"
export GOPATH="$HOME/go"
if [ -f /etc/agentbox/proxy.conf ]; then export $(grep -v '^#' /etc/agentbox/proxy.conf | xargs); fi
eval "$(starship init zsh)"
command -v mise &>/dev/null && eval "$(mise activate zsh)"
cd /workspace 2>/dev/null || true
ZSHRC
chown agent:agent /home/agent/.zshrc

# --- Secure secrets setup (runs for both pre-built and stock) ---
# Create secure claude wrapper if not already present
if [ ! -f /usr/bin/claude-real ]; then
    CLAUDE_PATH=$(which claude 2>/dev/null || true)
    if [ -n "$CLAUDE_PATH" ] && [ "$CLAUDE_PATH" != "/usr/local/bin/claude" ]; then
        mv "$CLAUDE_PATH" /usr/bin/claude-real
        cat > /usr/local/bin/claude << 'WRAPPER'
#!/bin/bash
# Secure wrapper - reads API key from root-only file
# Key is never visible via 'env' or 'echo $ANTHROPIC_API_KEY'
KEY=$(sudo cat /etc/agentbox/secrets/ANTHROPIC_API_KEY 2>/dev/null)
[ -n "$KEY" ] && export ANTHROPIC_API_KEY="$KEY"
exec /usr/bin/claude-real "$@"
WRAPPER
        chmod +x /usr/local/bin/claude
    fi
fi
mkdir -p /etc/agentbox/secrets
chmod 700 /etc/agentbox/secrets
cat > /etc/sudoers.d/agentbox-secrets << 'SUDOERS'
agent ALL=(root) NOPASSWD: /bin/cat /etc/agentbox/secrets/*
SUDOERS
chmod 0440 /etc/sudoers.d/agentbox-secrets

# --- Mark Ready ---
touch /etc/agentbox-ready
echo ""
echo "=========================================="
echo "AgentBox provisioning complete!"
if [ "$PREBUILT" = true ]; then
    echo "(Pre-built image - fast mode)"
else
    echo "(Full install from stock Ubuntu)"
fi
echo "=========================================="
`, cfg.Network.ProxyPort)
}

// generateProvisionScriptGasTown creates a provision script for Gas Town rigs
// Builds the rig automatically during provisioning using HTTPS (no SSH needed for public repos)
func generateProvisionScriptGasTown(cfg *config.Config, rigName string, repoURL string) string {
	// Get the base provision script
	baseScript := generateProvisionScript(cfg)

	// Add Gas Town rig creation during provisioning
	gasTownSetup := fmt.Sprintf(`
# --- Gas Town Rig Setup ---
echo "Setting up Gas Town rig..."
RIG_NAME="%s"
REPO_URL="%s"

# Set up directories
sudo -u agent mkdir -p /home/agent/gt
sudo -u agent mkdir -p /home/agent/.local/bin

# Set GT_ROOT in agent's environment
if ! grep -q "GT_ROOT" /home/agent/.zshrc 2>/dev/null; then
    echo 'export GT_ROOT=/home/agent/gt' >> /home/agent/.zshrc
fi

# Check if gt is available
GT_BIN="/home/agent/go/bin/gt"
if [ ! -x "$GT_BIN" ]; then
    echo "ERROR: gt not found at $GT_BIN"
    echo "Gas Town rig setup skipped - install gt and run: gt install ~/gt && gt rig add $RIG_NAME $REPO_URL"
else
    # First: Initialize Gas Town HQ (workspace)
    # This creates the town structure that gt rig add requires
    echo "Initializing Gas Town HQ..."
    sudo -u agent bash -c "
        export PATH='/usr/bin:/bin:/usr/local/bin:/home/agent/go/bin:/usr/local/go/bin:\$PATH'
        export GOPATH=/home/agent/go
        export HOME=/home/agent
        cd /home/agent/gt
        $GT_BIN install . --name agentbox --git 2>&1
    " && {
        echo "Gas Town HQ initialized!"
    } || {
        echo "Warning: gt install failed"
    }

    # Second: Add the rig to the workspace
    echo "Creating Gas Town rig: $RIG_NAME"
    echo "Repository: $REPO_URL"
    sudo -u agent bash -c "
        export PATH='/usr/bin:/bin:/usr/local/bin:/home/agent/go/bin:/usr/local/go/bin:\$PATH'
        export GT_ROOT=/home/agent/gt
        export GOPATH=/home/agent/go
        export HOME=/home/agent
        cd /home/agent/gt
        $GT_BIN rig add '$RIG_NAME' '$REPO_URL' 2>&1
    " && {
        echo "Gas Town rig '$RIG_NAME' created successfully!"
    } || {
        echo "Warning: gt rig add failed"
        echo "You can manually run: cd ~/gt && gt rig add $RIG_NAME $REPO_URL"
    }
fi

# Add useful aliases
if ! grep -q "alias crew=" /home/agent/.zshrc 2>/dev/null; then
    echo 'alias crew="cd \$GT_ROOT/*/crew 2>/dev/null || cd \$GT_ROOT"' >> /home/agent/.zshrc
fi

# Set default working directory to the rig
echo 'cd /home/agent/gt/%s 2>/dev/null || cd /home/agent/gt || true' >> /home/agent/.zshrc

echo "Gas Town setup complete"
`, rigName, repoURL, rigName)

	// Insert the Gas Town setup before the "Mark Ready" section
	return strings.Replace(baseScript, "# --- Mark Ready ---", gasTownSetup+"\n# --- Mark Ready ---", 1)
}
