package lima

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/davidsenack/agentbox/internal/config"
)

const limaTemplateContent = `# AgentBox Lima VM Configuration
# Generated by agentbox - do not edit manually

vmType: "vz"
vmOpts:
  vz:
    rosetta:
      enabled: true
      binfmt: true

cpus: {{ .Config.VM.CPUs }}
memory: "{{ .Config.VM.Memory }}"
disk: "{{ .Config.VM.Disk }}"

images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"

# CRITICAL: Only mount workspace and artifacts - nothing else
mounts:
  - location: "{{ .WorkspacePath }}"
    mountPoint: "/workspace"
    writable: true
  - location: "{{ .ArtifactsPath }}"
    mountPoint: "/artifacts"
    writable: true

# Network: use Lima's default networking (user-v2)
# This provides outbound internet access and host connectivity via socket forwarding

# SSH configuration - no forwarding
ssh:
  localPort: 0
  forwardAgent: false
  forwardX11: false

# Provision scripts run as root
provision:
  - mode: system
    script: |
{{ .ProvisionScript | indent 6 }}

# Readiness probe
probes:
  - mode: readiness
    description: "Waiting for agentbox setup"
    script: |
      #!/bin/bash
      test -f /etc/agentbox-ready
    hint: "Run 'agentbox reset <name>' if this fails"

# Environment propagation is disabled - secrets injected explicitly
propagateProxyEnv: false

# Plain mode disabled - we need cloud-init for user creation
plain: false

# CA certificates - keep defaults
caCerts:
  removeDefaults: false

# Containerd disabled - no Docker socket
containerd:
  system: false
  user: false
`

func indent(spaces int, v string) string {
	pad := strings.Repeat(" ", spaces)
	lines := strings.Split(v, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = pad + line
		}
	}
	return strings.Join(lines, "\n")
}

// GenerateTemplate creates a Lima YAML template for the given configuration
func GenerateTemplate(cfg *config.Config, projectDir string) (string, error) {
	funcMap := template.FuncMap{
		"indent": func(spaces int, v string) string {
			return indent(spaces, v)
		},
	}

	tmpl, err := template.New("lima").Funcs(funcMap).Parse(limaTemplateContent)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	provisionScript := generateProvisionScript(cfg)

	data := struct {
		Config          *config.Config
		WorkspacePath   string
		ArtifactsPath   string
		ProvisionScript string
	}{
		Config:          cfg,
		WorkspacePath:   filepath.Join(projectDir, "workspace"),
		ArtifactsPath:   filepath.Join(projectDir, "artifacts"),
		ProvisionScript: provisionScript,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

func generateProvisionScript(cfg *config.Config) string {
	return fmt.Sprintf(`#!/bin/bash
set -euo pipefail

# =============================================================================
# AgentBox Guest Provisioning Script
# Network is OPEN - proxy is used for API key injection only
# =============================================================================

export DEBIAN_FRONTEND=noninteractive

echo "Starting AgentBox provisioning..."

# --- User Creation ---
if ! id -u agent >/dev/null 2>&1; then
    echo "Creating agent user..."
    useradd -m -s /bin/zsh -G sudo agent
    echo "agent ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/agent
    chmod 0440 /etc/sudoers.d/agent
fi

# --- Proxy Configuration ---
# Proxy is optional - used for API key injection to configured hosts
# Get host gateway from default route (try lima0 first, fall back to any default)
HOST_GATEWAY=$(ip route | grep "default.*lima0" | head -1 | awk '{print $3}' || true)
if [ -z "$HOST_GATEWAY" ]; then
    HOST_GATEWAY=$(ip route | grep default | head -1 | awk '{print $3}' || true)
fi
PROXY_PORT=%d
PROXY_URL="http://${HOST_GATEWAY}:${PROXY_PORT}"

echo "Configuring proxy: ${PROXY_URL}"

# Set system-wide proxy in /etc/environment (read by PAM for all shells)
cat >> /etc/environment << EOF
HTTP_PROXY="${PROXY_URL}"
HTTPS_PROXY="${PROXY_URL}"
http_proxy="${PROXY_URL}"
https_proxy="${PROXY_URL}"
NO_PROXY="localhost,127.0.0.1,::1"
no_proxy="localhost,127.0.0.1,::1"
EOF

# Export for current script
export HTTP_PROXY="${PROXY_URL}"
export HTTPS_PROXY="${PROXY_URL}"
export http_proxy="${PROXY_URL}"
export https_proxy="${PROXY_URL}"

# --- System Packages ---
echo "Installing system packages..."
apt-get update
apt-get install -y \
    zsh \
    build-essential \
    curl \
    wget \
    git \
    jq \
    ripgrep \
    fzf \
    tmux \
    neovim \
    unzip \
    ca-certificates \
    gnupg

# --- Node.js (via NodeSource for latest LTS) ---
echo "Installing Node.js..."
mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
apt-get update
apt-get install -y nodejs

# --- Python 3 ---
echo "Installing Python..."
apt-get install -y python3 python3-pip python3-venv

# --- Go ---
echo "Installing Go..."
GO_VERSION="1.22.0"
ARCH=$(dpkg --print-architecture)
curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz" | tar -C /usr/local -xzf -
echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/go.sh

# --- Starship Prompt ---
echo "Installing Starship..."
curl -fsSL https://starship.rs/install.sh | sh -s -- -y

# --- mise (version manager) ---
echo "Installing mise..."
curl -fsSL https://mise.run | sh
mv /root/.local/bin/mise /usr/local/bin/mise 2>/dev/null || true

# --- Agent User Setup ---
echo "Configuring agent environment..."

# Set zsh as default shell
chsh -s /bin/zsh agent

# Create agent directories
sudo -u agent mkdir -p /home/agent/.local/bin
sudo -u agent mkdir -p /home/agent/.config/nvim

# --- Oh My Zsh ---
echo "Installing Oh My Zsh..."
sudo -u agent sh -c 'RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

# --- Agent .zshrc ---
cat > /home/agent/.zshrc << 'ZSHRC'
# AgentBox zsh configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git fzf)
source $ZSH/oh-my-zsh.sh

# Environment
export PATH="$HOME/.local/bin:/usr/local/go/bin:$PATH"
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

# Proxy (for API key injection)
if [ -f /etc/environment ]; then
    export $(grep -v '^#' /etc/environment | xargs)
fi

# Starship prompt
eval "$(starship init zsh)"

# mise (version manager)
if command -v mise &> /dev/null; then
    eval "$(mise activate zsh)"
fi

# Start in workspace
cd /workspace 2>/dev/null || true
ZSHRC

chown agent:agent /home/agent/.zshrc

# --- Neovim Config ---
cat > /home/agent/.config/nvim/init.lua << 'NVIMCONFIG'
-- AgentBox Neovim configuration
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.cursorline = true
vim.opt.termguicolors = true
vim.opt.signcolumn = "yes"
vim.opt.clipboard = "unnamedplus"
vim.opt.ignorecase = true
vim.opt.smartcase = true

-- Key mappings
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>w", ":w<CR>")
vim.keymap.set("n", "<leader>q", ":q<CR>")
NVIMCONFIG

chown -R agent:agent /home/agent/.config

# --- Install AI Tools as agent user ---
echo "Installing AI coding tools..."

# claude-code
sudo -u agent bash -c 'export PATH="/usr/local/go/bin:$PATH"; npm install -g @anthropic-ai/claude-code' || echo "claude-code install failed (may need API key)"

# opencode
sudo -u agent bash -c 'export PATH="/usr/local/go/bin:$PATH"; export GOPATH="$HOME/go"; /usr/local/go/bin/go install github.com/opencode-ai/opencode@latest' || echo "opencode install failed"

# --- Mount Permissions ---
echo "Mount points ready: /workspace, /artifacts"

# --- Mark Ready ---
touch /etc/agentbox-ready
echo ""
echo "=========================================="
echo "AgentBox provisioning complete!"
echo "=========================================="
echo "Installed: zsh, oh-my-zsh, starship, tmux"
echo "Installed: node, python, go, mise"
echo "Installed: neovim, ripgrep, fzf, jq"
echo "Installed: claude-code, opencode"
echo "=========================================="
`, cfg.Network.ProxyPort)
}
